# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e55a2c76919837f44497162a7e09f943a2952037ef76dd86330a275fde7afa8d5ae650e40b1f648e56b67589cc8cd110db8af669b07f572565b674a63c9bce8

test:
  secret_key_base: b3377fa0f4a979d6d531053b91bab021c375775659fd3ccfa084a70683fa259e95e8e3a600cfb826b691c189006500148482af03c777b97c138fee1564b2272d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
